name: Build C Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build app for release
      run: msbuild VS\Downloader.csproj -t:rebuild -verbosity:diag -property:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-artifact
        path: downloader.exe