name: Build C Project

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: msbuild /p:Configuration=Release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-artifact
        path: downloader.exe